### ISSUE TITLE
create_autospec causes error in python3.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#249]
```
What steps will reproduce the problem?
1. mock.create_autospec(someClass)

What is the expected output? What do you see instead?
AttributeError: 'method-wrapper' object has no attribute '__module__'

What version of the product are you using? On what operating system?
10.1
Ubuntu
python3.4

This works fine with python2.7

Please provide any additional information below.


```

Original issue reported on code.google.com by `Louise.S...@gmail.com` on 6 Apr 2015 at 10:08

**Comment by rbtcollins** [comment]
Fixed in 1.1.0 (though there may still be a bug in the fix - see #264 )
