### ISSUE TITLE
functools.partial object has no attribute 'func_defaults'

### ISSUE THREAD

**Issue by hlieberman** [testing-cabal/mock#323]
Hello everyone,

With a new version of mock (1.3.0), I am getting an error on a couple of the letsencrypt tests which previously worked.  The error appears to track down into mock itself.

```
======================================================================
ERROR: test_perform_test_mode (letsencrypt.plugins.manual_test.ManualAuthenticatorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1450, in __enter__
    _name=self.attribute, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 2320, in create_autospec
    _name='()', _parent=mock)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 2359, in create_autospec
    _check_signature(original, new, skipfirst=skipfirst)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 228, in _check_signature
    _copy_func_details(func, checksig)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 254, in _copy_func_details
    funcopy.func_defaults = func.func_defaults
AttributeError: 'functools.partial' object has no attribute 'func_defaults'

----------------------------------------------------------------------
```

The test that fails is located here: https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt/plugins/manual_test.py

FYI @Kuba

**Comment by hlieberman** [comment]
More details:

The branch checking for Python2 in mock.py L251 will cause a problem when using autospec and a class instance.

functools.partial objects don't support func_defaults, and the combination of autospec and class instances will cause it to be called.

**Comment by kuba** [comment]
I found that you cannot `autospec=True` for `socket.socket`.

**Comment by rbtcollins** [comment]
Hmm, so we need a backport of functools too?

**Comment by poros** [comment]
Is anyone working on a fix? I got bitten by this, too :(

**Comment by rbtcollins** [comment]
There is a backport of functools - functools32 - but its quite stale; I may look into adopting it. For now though - please confirm that these cases do work on CPython itself - 3.5 or newer.

**Comment by cjw296** [comment]
I think this should be fixed in bf8efd2, if there are further problems, please comment and we can re-open.
